#!/bin/bash
sudo apt update
sudo apt upgrade
sudo journalctl --rotate --vacuum-size=350M
sudo apt autoremove
sudo apt autoclean # clean outdated packages
sudo find ~/.cache/ -type f -atime +183 -delete # delete .cache files that are more than 6 months old
#Removes old revisions of snaps: #CLOSE ALL SNAPS BEFORE RUNNING THIS
set -eu
LANG=en_US.UTF-8 snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        sudo snap remove "$snapname" --revision="$revision"
    done
