#!/bin/bash
#whitepngtotransparent
usage()
{
    echo 'Usage: whitepngtotransparent "argument(s)" [-o dir] [-rm]'
    echo ""
    echo "Converts the white background of png/jpg files to transparent files."
    echo ""
    echo "-o dir : pour placer les nouveaux fichiers dans le répertoire dir"
    echo "-rm : pour effacer les fichiers .png convertis"
    echo ""
    echo "-h or --help Print this message"
}


if [ $# = 0 ]
then
	usage
fi

let "a=0"
let "erase=0"
let "move=0"
declare -a newfiles
declare -a firstfiles


while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        -rm)
            let "erase=1"
	    ;;
        -o)
	    let "move=1"
	    shift
	    directory="$1"
	    if [ ! -e "$directory" ]
	    then
		mkdir $directory
	    fi
            ;;
	*)
	    IFS='.' read -ra split <<< "$1" #in order to split $1 in an array with delimiter '.'
	    if [ "${split[1]}" == "png" ]
	    then
		if [ -e "$1" ]
		then
		    #convert "$1" -fuzz 2% -transparent white "${split[0]}_transparent.png"
            #convert "$1" ( -clone 0 -fill "#a0132e" -colorize 100 ) ( -clone 0,1 -compose difference -composite -separate +channel -evaluate-sequence max-auto-level ) -delete 1 -alpha off -compose over -compose copy_opacity -composite "${split[0]}_transparent.png"
            color2alpha -ca white "$1" "${split[0]}_transparent.png"
		    echo -e "\e[92m$1 \e[39m transformed to transparent."
		    let "a=a+1"
		    firstfiles+=("$1")
		    newfiles+=("${split[0]}_transparent.png")
		else
		    echo -e "\e[31m--- $1 \e[39mdoesn't seems to exist..."
		fi
	    else
		echo -e "\e[91m--- $1 \e[39mnot a .png file"
	    fi
            ;;
    esac
    shift
done

if [ $a -lt 2 ]
then
   echo -e "\e[39m$a files created."
else
   echo -e "\e[39m$a file created."
fi

#erase step :
if [ $erase -eq 1 ]; then

    echo""
    # for file in ${firstfiles[*]}
    # do
    # 	rm "$file"
    # 	echo "$file erased"
    # done
    for ((i = 0; i < ${#firstfiles[@]}; i++))
    do
	rm "${firstfiles[$i]}"
	echo "${firstfiles[$i]} removed"
    done
fi

#move step :
if [ $move -eq 1 ]; then

    echo""
    #this doesn't work because of spaces in names
    # for file in ${newfiles[*]}
    # do
    # 	mv "$file" "$directory"
    # 	echo "$file moved"
    # done
    #instead use :
    for ((i = 0; i < ${#newfiles[@]}; i++))
    do
	mv "${newfiles[$i]}" "$directory"
	echo "${newfiles[$i]} moved"
    done
fi
IFS=' '
